export const tweetsData = [   
    
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Thur Dec 15, 2022] #100DaysOfCode Day 096: Scrimba - Frontend Developer Career Path. Next Level Javascript: object destructuring and applying to rendering html` ,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc096',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Wed Dec 14, 2022] #100DaysOfCode Day 095: 1) Updated gingerkiwi.blog including creating new repo with git workspace. 2) Scrimba - Frontend Developer Career Path. Started Next Level Javascript ` ,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc095',
    },

    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Sun Dec 11, 2022] #100DaysOfCode Day 094: Scrimba - Frontend Developer Career Path. The new version of module 6: Responsive Design. Media queries and mobile first design ` ,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc094',
    },
    // {
    //     handle: `@GingerKiwiDev`,
    //     profilePic: `images/avatar.png`,
    //     likes: 1,
    //     retweets: 0,
    //     tweetText: `[Sat Dec 10, 2022] #100DaysOfCode Day 093: `,
    //     replies: [],
    //     isLiked: true,
    //     isRetweeted: false,
    //     uuid: '4b161eee-c0f5-4545-9c4b-856294422doc093',
    // },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Dec 09, 2022] #100DaysOfCode Day 092: Scrimba - Frontend Developer Career Path. Now I'm 45% done! CSS review of ems vs rem, flexbox layout. `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc092',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Thur Dec 08, 2022] #100DaysOfCode Day 091: Scrimba - Frontend Developer Career Path. Finished building a co-working space site responsive design including position relative, absoulte, and fixed: https://scrimba.com/playlist/pQrEKCD. `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc091',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Wed Dec 07, 2022] #100DaysOfCode Day 090: Scrimba - Frontend Developer Career Path. XXXXXXXXXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc090',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Tue Dec 06, 2022] #100DaysOfCode Day 089: Scrimba - Frontend Developer Career Path. XXXXXXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc089',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Mon Dec 05, 2022] #100DaysOfCode Day 088: Scrimba - Frontend Developer Career Path. XXXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc088',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Sun Dec 04, 2022] #100DaysOfCode Day 087: Scrimba Continued with Learn Tailwind course `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc087',
    },
    
    
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Sat Dec 03, 2022] #100DaysOfCode Day 086: Scrimba - Started Learn Tailwind CSS course `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc086',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Dec 02, 2022] #100DaysOfCode Day 085: Scrimba - Frontend Developer Career Path. XXXXXXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc083',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Thur Dec 01, 2022] #100DaysOfCode Day 084: Scrimba - Frontend Developer Career Path. XXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc084',
    },
    
    
    
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Wed Nov 30, 2022] #100DaysOfCode Day 083: Scrimba - Frontend Developer Career Path. XXXXXX `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc083',
    },

// XXXX
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Tue Nov 29, 2022] #100DaysOfCode Day 082: Scrimba - Frontend Developer Career Path. The new version of module 6: Responsive Design. Skipped ahead to CSS Grid (because I'd finished the older version of this module). Reviewed grid basics and fr units. Learned grid areas and media queries. `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc082',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Mon Nov 28, 2022] #100DaysOfCode Day 081: Change of pace today. I did a lot of going through SaaS website code, especially landing pages. Getting design, code, and content ideas for Dreaming Cat Productions project. `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc081',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Sun Nov 27, 2022] #100DaysOfCode Day 080: Initialized workspace for Dreaming Cat Productions. Started on coding website, especially the css. Deployed on Netlify to temp url: https://dreamingcatproductions.netlify.app so site will have continuous deployment `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc080',
    },

    // SAT NOV 26TH WAS ROCKCLIMBING WITH TORONTOJS
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 25, 2022] #100DaysOfCode Day 079: Got this personal version of Twitter up so I can keep track of my 100 Days Of Code. It's frontend only, but so easy to update daily as it's hosted on Netlify and connected to GitHub `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc079',
    },

    //
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 25, 2022] Will be filling in #100DaysOfCode record from day 068-078 here soon`,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422twt001',
    },


    // NEED TO FILL IN WORK HERE

    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 12, 2022] #100DaysOfCode Day 067: I started the Code Reviews module in Scrimba Frontend Developer Career Path today. Just like when I started teaching, this is a whole new mindset (and a wee bit intimidating ... but learning happens when you're uncomfortable so it's a good thing).

        I did some more of the final section in Essential Javascript Concepts, including forEach() and a nice section on one of my favourite CDNs, Font Awesome.  `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc067',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Thur, Nov 11, 2022] #100DaysOfCode Day 066: Today I got a new site design up for https://www.gingerkiwi.dev
        This included renewing the SSL cert and uploading files to a classic cPanel. I'll be migrating my domain hosting to Netlify in December.  `,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc066',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 25, 2022] Will be filling in #100DaysOfCode record from day 061-065 here soon`,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422twt002',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 27,
        retweets: 10,
        tweetText: `[Fri Nov 04, 2022] #100DaysOfCode Day 060: Wrote project management doc for my open source repo https://t.co/14sQlAQKxh created issue for contributors to work on. Hours coding new blog design. Plus a quick ‘under renovation’ version because …continued (1 of 2)
        `,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ef',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 04]… (2nd of 2)\nThree recruiters contacted me on LinkedIn today about technical writing contracts. So I need something up on https://t.co/HyLMgjABh5 . Thanks to @scrimba and Andrew of Andrew’s Coffee Chats and @torontojs https://t.co/xXI0TWj1lZ for help with my LinkedIn profile!`,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422doc060b',
    },
    {
        handle: `@GingerKiwiDev`,
        profilePic: `images/avatar.png`,
        likes: 1,
        retweets: 0,
        tweetText: `[Fri Nov 25, 2022] Will be filling in #100DaysOfCode record from day 001-060 from downloaded Twitter account data soon`,
        replies: [],
        isLiked: true,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-856294422twt001',
    },
    {
        handle: `@Mastodon`,
        profilePic: `images/mastodon.png`,
        likes: 28243,
        retweets: 12980,
        tweetText: `I nominate @@Elon ✅ for the Mars trip!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223zz',
    },   
    {
        handle: `@TrollBot66756542 💎`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {
        handle: `@Elon ✅`,
        profilePic: `images/musk.png`,
        likes: 6500,
        retweets: 234,
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  {
                handle: `@TomCruise ✅`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
                  {
                handle: `@ChuckNorris ✅`,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
        {
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {
                handle: `@StackOverflower ☣️`,
                profilePic: `images/overflow.png`,
                tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
            },
            {
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `You are wonderful just as you are! ❤️`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },     
]
